#!/bin/bash
set -e

rm -rf venv
python3.8 -m virtualenv venv

# Install package
./venv/bin/pip install --no-cache-dir -r requirements.txt
./venv/bin/pip install --no-cache-dir .

# Static analysis (without changing files)
./venv/bin/pip install --no-cache-dir mypy flake8 flake8-bugbear flake8-pie pep8-naming flake8-simplify flake8-fixme flake8-cognitive-complexity
# Linting (with changing files)
./venv/bin/pip install --no-cache-dir black isort
# Security checks and other metrics
./venv/bin/pip install --no-cache-dir bandit radon safety
