#!/bin/bash
set -e

echo -e "Code Security Checks (bandit):"
echo
./venv/bin/bandit --quiet -r smartpost
echo "----------"

echo -e "Dependencies Security Checks (safety):"
echo
./scripts/safety-2.3.2 check --full-report
echo "----------"

echo -e "Checking outdated dependencies (pip):"
echo
./venv/bin/pip list --outdated
echo "----------"
