#!/bin/bash
set -e

# Go to repository root directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${DIR}/.."

find smartpost -type f -name "*.py[co]" -delete
find smartpost -type d -name __pycache__ -delete

rm -rf dist build *.egg-info

python3.11 -m build --wheel
twine upload dist/*

rm -rf dist build *.egg-info
